---
version: '3.7'
services:
  database:
    image: 'postgres:14-alpine'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: test # The PostgreSQL user (useful to connect to the database)
      POSTGRES_PASSWORD: test # The PostgreSQL password (useful to connect to the database)
      POSTGRES_DB: test # The PostgreSQL default database (automatically created at first launch)